language: node_js
node_js:
  - 4
  - 6
  - 7
branches:
  only:
    - master
cache:
  directories:
    - node_modules
sudo: false
script:
    - npm run lint
    - npm run test -- --coverage
    - npm run build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
